SUBMODULE_ARCHITECTURE := architecture
SUBMODULE_IMPLEMENTATION := implementation
SUBMODULE_DEMO := demo

SUBMODULES := $(SUBMODULE_ARCHITECTURE) $(SUBMODULE_IMPLEMENTATION) $(SUBMODULE_DEMO)


.PHONY: all
all: $(SUBMODULE_DEMO)


$(SUBMODULE_DEMO): $(SUBMODULE_ARCHITECTURE) $(SUBMODULE_IMPLEMENTATION)

$(SUBMODULE_IMPLEMENTATION): $(SUBMODULE_ARCHITECTURE)

.PHONY: $(SUBMODULES)
$(SUBMODULES):
	$(MAKE) --directory=$@
